  docker-build:
    runs-on: ubuntu-latest
    needs: [unit-tests, sast]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region us-east-1
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build and Push to ECR
        run: |
          docker build -t myapp .
          docker tag myapp:latest ${{ secrets.ECR_REPO }}/myapp:latest
          docker push ${{ secrets.ECR_REPO }}/myapp:latest

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: |
          docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
